language: python

python:
  - "3.9"

before_script:
  - cd mysite
  - python manage.py migrate
  - python manage.py collectstatic --noinput

before_install:
  - wget "https://www.sqlite.org/2020/sqlite-autoconf-3320100.tar.gz"
  - tar xzf sqlite-autoconf-3320100.tar.gz
  - cd sqlite-autoconf-3320100
  - ./configure --prefix=/usr/local
  - make
  - sudo make install
  - cd ..

install:
  - pip install -r requirements.txt

script:
  - black --check .
  - flake8 .
  - coverage run manage.py test polls

after_success: 
  - coveralls

deploy:
  provider: elasticbeanstalk
  access_key_id: $AWS_EB_ACCESS_KEY
  secret_access_key: $AWS_EB_SECRET_ACCESS_KEY
  region: "us-west-2"
  app: "mysite-dev2"
  env: "mysite-dev2"
  bucket_name: $AWS_EB_BUCKET_NAME
