language: python

python:
  - "3.9"

install:
  - pip install -r requirements.txt
  - pip install black
  - pip install flake8
  - pip install coverage
  - pip install coveralls

before_script:
  - cd mysite
  - python manage.py migrate
  - python manage.py collectstatic --noinput

script:
  - black --check .
  - flake8 .

after_success: 
  - coveralls

deploy:
  provider: elasticbeanstalk
  access_key_id: $AWS_EB_ACCESS_KEY
  secret_access_key: $AWS_EB_SECRET_ACCESS_KEY
  region: "us-west-2"
  app: "swe1-app-master"
  env: "swe1-app-master-env"
  bucket_name: ""
